source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in testApp.gemspec
gemspec

gem 'analytics-ruby', '~> 2.0.0', :require => 'segment/analytics'